-- Module 3 seed: positions (24) + staff (32) with the ORIGINAL ids.
-- Re-runnable: on conflict do nothing. Ids must never change — prior data
-- (responses.position_id, step_link_targets.position_id, assignments.person_id,
-- step_decisions.*) is keyed to them.

insert into positions (id, name, grp, sort_order) values
  ('ceo','Chief Executive Officer (Co)','Executive',0),
  ('head_commercial','Head of Commercial','Commercial',1),
  ('snr_commercial','Senior Commercial Officer','Commercial',2),
  ('project_mgmt','Project Management (Creative Solution)','Commercial',3),
  ('head_production','Head of Production','Production',4),
  ('chief_producer','Chief Producer','Production',5),
  ('producer','Producer','Production',6),
  ('script_doctor','Script Doctor','Production',7),
  ('script_writer','Junior Script Writer','Production',8),
  ('casting_mgr','Casting Manager','Production',9),
  ('casting_officer','Casting Officer','Production',10),
  ('creative_mgr','Creative Solution Manager','Production',11),
  ('snr_editor','Senior Video Editor','Production',12),
  ('vdo_editor','VDO Editor','Production',13),
  ('graphic_designer','Graphic Designer','Production',14),
  ('snr_social','Senior Social Media Executive','Production',15),
  ('social_creator','Social Media Content Creator Officer','Production',16),
  ('head_operation','Head of Operation','Operation',17),
  ('business_planner','Business Planner','Operation',18),
  ('snr_cost','Senior Cost Control Officer','Operation',19),
  ('cost_control','Cost Control Officer','Operation',20),
  ('snr_revenue','Senior Revenue Control Officer','Operation',21),
  ('hr_officer','HR Officer','Operation',22),
  ('legal','Senior Legal Counsel','Operation',23)
on conflict (id) do nothing;

insert into staff (id, nick, position_id, unit, sort_order) values
  ('mj','MJ','ceo',null,0),
  ('ling','หลิง','ceo',null,1),
  ('mag','แม็ก','head_commercial',null,2),
  ('oil','ออย','snr_commercial',null,3),
  ('bell','เบล','project_mgmt',null,4),
  ('off','อ๊อฟ','head_production',null,5),
  ('oh','โอ๋','chief_producer',null,6),
  ('may','เมย์','chief_producer',null,7),
  ('tuk','ตุ๊ก','producer','Unit 1',8),
  ('kae','เก๋','producer','Unit 1',9),
  ('dream','ดรีม','producer','Unit 1',10),
  ('nokhook','นกฮูก','producer','Unit 1',11),
  ('faifai','ฝ้ายฝ้าย','producer','Unit 2',12),
  ('noon','นุ่น','producer','Unit 2',13),
  ('pa','พา','producer','Unit 2',14),
  ('naitan','นายท่าน','script_doctor',null,15),
  ('kwang','กวาง','script_writer',null,16),
  ('chik','ฉิก','casting_mgr',null,17),
  ('ploy_cast','พลอย','casting_officer',null,18),
  ('a','เอ','creative_mgr',null,19),
  ('man','แมน','snr_editor',null,20),
  ('chin','ชิน','vdo_editor',null,21),
  ('new','นิว','graphic_designer',null,22),
  ('fai','ฝ้าย','snr_social',null,23),
  ('gem','เจม','social_creator',null,24),
  ('praew','แพรว','head_operation',null,25),
  ('bangern','บังเอิญ','business_planner',null,26),
  ('yui','หยุย','snr_cost',null,27),
  ('noey','เนย','cost_control',null,28),
  ('aoy','อ้อย','snr_revenue',null,29),
  ('ploy_hr','พลอย','hr_officer',null,30),
  ('hat','ฮาท','legal',null,31)
on conflict (id) do nothing;
